Add more categories support
pelican-plugins/neighbors pull request #6
Opened 2021-04-07 08:22 UTC by johnmathews

This change adds support for the `more_categories` plugin, allowing users to show neighbors based on a custom level of subcategory. It copies the approach used for the `subcategories` plugin.

It doesn't change the existing support for the `subcategories` plugin.

### why is this necessary?
`more_categories` offers support for subcategories and also multiple categories, `subcategories` doesn't offer support for multiple categories.

Also, `subcategories` hasn't been updated recently and isn't in the new Pelican plugins directory. `more_categories` is in the Pelican plugins organization. Therefore it seems preferable to support the `more_categories` plugin in preference to the `subcategories` plugin.

2021-04-07 09:25 UTC, johnmathews commented
I've noticed that in the settings in the PLUGINS list, `more_categories` should be listed before `neighbors`. 

If the plugins are not listed in this order then it seems that `neighbors` cannot see an articles subcategories.

Is this a problem or is it expected?

2021-04-07 09:36 UTC, justinmayer requested changes
Many thanks for the contribution, John! I made a few minor suggestions regarding plugin name conventions and other trivial items in the README. Would you mind taking a look and addressing those comments? Thanks again! 😁

2021-04-07 09:36 UTC, justinmayer commented on README.md
> +## more_categories plugin support
The plugin naming convention that we've been using for migrated plugins is a bit more human-focused. Would you mind changing "more_categories" to "More Categories"? Also, please add a blank line after Markdown headings.

2021-04-07 09:36 UTC, justinmayer commented on README.md
> +You can use `Neighbors` with the [`more_categories`](https://github.com/pelican-plugins/more-categories) plugin.
`Neighbors` → the Neighbors plugin

`more_categories` → More Categories

2021-04-07 09:36 UTC, justinmayer commented on README.md
> +You can use `Neighbors` in conjunction with the [`Subcategory`
`Neighbors` → the Neighbors plugin

`Subcategory` → Subcategory

2021-04-07 09:36 UTC, justinmayer commented on README.md
> +## template examples
template examples → Template Examples

2021-04-07 09:36 UTC, justinmayer commented on README.md
> +The usage with subcategories from either `subcategory` or `more_categories` is:
from either `subcategory` or `more_categories` is → from either the Subcategory plugin or the More Categories plugin is:

2021-04-07 09:36 UTC, justinmayer commented on pelican/plugins/neighbors/neighbors.py
> +    # support for more_categories plugin
`# Support for the More Categories plugin`

2021-04-07 09:36 UTC, justinmayer commented on pelican/plugins/neighbors/neighbors.py
> +    # support for subcategory plugin
`# Support for the Subcategory plugin`

2021-04-07 09:44 UTC, justinmayer requested changes
By the way, shouldn't the limitation mentioned in the pull request description also be documented in the Neighbors plugin README?

2021-04-07 09:44 UTC, justinmayer commented on README.md
> +- `sebcategory0` is `foo`
`sebcategory0` → `subcategory0`

2021-04-07 09:53 UTC, justinmayer commented
> I've noticed that in the settings in the PLUGINS list, `more_categories` should be listed before `neighbors`. If the plugins are not listed in this order then it seems that `neighbors` cannot see an articles subcategories. Is this a problem or is it expected?

Well, it's both expected and a bit of a problem, albeit one that can't be easily addressed within Pelican itself. Plugins are currently implemented via [Blinker](https://github.com/jek/blinker), which does not support plugin ordering. So if you want to use a plugin that depends on another plugin, you can't use the implicit automatic namespace plugin loading in Pelican 4.5+ and must instead explicitly enumerate and order plugins accordingly in the `PLUGINS` list.

2021-05-04 15:28 UTC, justinmayer commented
Thanks, John! Merged manually and released as Neighbors 1.2. 🎉

2021-05-04 15:28 UTC, closed without merging